/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgregarRouteImport } from './routes/agregar'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as CompletarIdRouteImport } from './routes/completar.$id'
import { Route as EvaluarIdRouteImport } from './routes/evaluar.$id'
import { Route as PorQueIdRouteImport } from './routes/por-que.$id'
import { Route as RestauranteIdRouteImport } from './routes/restaurante.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgregarRoute = AgregarRouteImport.update({
  id: '/agregar',
  path: '/agregar',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletarIdRoute = CompletarIdRouteImport.update({
  id: '/completar/$id',
  path: '/completar/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluarIdRoute = EvaluarIdRouteImport.update({
  id: '/evaluar/$id',
  path: '/evaluar/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PorQueIdRoute = PorQueIdRouteImport.update({
  id: '/por-que/$id',
  path: '/por-que/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RestauranteIdRoute = RestauranteIdRouteImport.update({
  id: '/restaurante/$id',
  path: '/restaurante/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agregar': typeof AgregarRoute
  '/favoritos': typeof FavoritosRoute
  '/mapa': typeof MapaRoute
  '/matches': typeof MatchesRoute
  '/completar/$id': typeof CompletarIdRoute
  '/evaluar/$id': typeof EvaluarIdRoute
  '/por-que/$id': typeof PorQueIdRoute
  '/restaurante/$id': typeof RestauranteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agregar': typeof AgregarRoute
  '/favoritos': typeof FavoritosRoute
  '/mapa': typeof MapaRoute
  '/matches': typeof MatchesRoute
  '/completar/$id': typeof CompletarIdRoute
  '/evaluar/$id': typeof EvaluarIdRoute
  '/por-que/$id': typeof PorQueIdRoute
  '/restaurante/$id': typeof RestauranteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agregar': typeof AgregarRoute
  '/favoritos': typeof FavoritosRoute
  '/mapa': typeof MapaRoute
  '/matches': typeof MatchesRoute
  '/completar/$id': typeof CompletarIdRoute
  '/evaluar/$id': typeof EvaluarIdRoute
  '/por-que/$id': typeof PorQueIdRoute
  '/restaurante/$id': typeof RestauranteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agregar'
    | '/favoritos'
    | '/mapa'
    | '/matches'
    | '/completar/$id'
    | '/evaluar/$id'
    | '/por-que/$id'
    | '/restaurante/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agregar'
    | '/favoritos'
    | '/mapa'
    | '/matches'
    | '/completar/$id'
    | '/evaluar/$id'
    | '/por-que/$id'
    | '/restaurante/$id'
  id:
    | '__root__'
    | '/'
    | '/agregar'
    | '/favoritos'
    | '/mapa'
    | '/matches'
    | '/completar/$id'
    | '/evaluar/$id'
    | '/por-que/$id'
    | '/restaurante/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgregarRoute: typeof AgregarRoute
  FavoritosRoute: typeof FavoritosRoute
  MapaRoute: typeof MapaRoute
  MatchesRoute: typeof MatchesRoute
  CompletarIdRoute: typeof CompletarIdRoute
  EvaluarIdRoute: typeof EvaluarIdRoute
  PorQueIdRoute: typeof PorQueIdRoute
  RestauranteIdRoute: typeof RestauranteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agregar': {
      id: '/agregar'
      path: '/agregar'
      fullPath: '/agregar'
      preLoaderRoute: typeof AgregarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/completar/$id': {
      id: '/completar/$id'
      path: '/completar/$id'
      fullPath: '/completar/$id'
      preLoaderRoute: typeof CompletarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluar/$id': {
      id: '/evaluar/$id'
      path: '/evaluar/$id'
      fullPath: '/evaluar/$id'
      preLoaderRoute: typeof EvaluarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/por-que/$id': {
      id: '/por-que/$id'
      path: '/por-que/$id'
      fullPath: '/por-que/$id'
      preLoaderRoute: typeof PorQueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurante/$id': {
      id: '/restaurante/$id'
      path: '/restaurante/$id'
      fullPath: '/restaurante/$id'
      preLoaderRoute: typeof RestauranteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgregarRoute: AgregarRoute,
  FavoritosRoute: FavoritosRoute,
  MapaRoute: MapaRoute,
  MatchesRoute: MatchesRoute,
  CompletarIdRoute: CompletarIdRoute,
  EvaluarIdRoute: EvaluarIdRoute,
  PorQueIdRoute: PorQueIdRoute,
  RestauranteIdRoute: RestauranteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
